disabled_rules:
- trailing_whitespace
- valid_docs
- type_name
- variable_name

excluded:
- reddift/vendor
- reddift.playground
- reddiftTests
- reddiftSample
- reddiftSampleTV

file_length:
  warning: 800
  error: 1000

line_length:
  warning: 800
  error: 1000

type_body_length:
  warning: 400
  error: 800

variable_name:
  max_length:
    warning: 50
    error: 40
  min_length:
    warning: 1
    error: 0

function_parameter_count:
  warning: 10
  error: 20

function_body_length:
  warning: 200
  error: 300

cyclomatic_complexity:
  warning: 50
  error: 100